name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build  # Se o diretório de build for diferente, ajuste aqui

      - name: Deploy para a branch pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout --orphan pages
          git rm -rf .
          mv build/* .  # Se for Vite, talvez seja "dist/*"
          git add .
          git commit -m "Deploy GitHub Pages"
          git push -f origin pages
