name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências do backend
        run: npm install

      - name: Instalar dependências do frontend
        run: |
          cd app
          npm install

      - name: Build do frontend
        run: |
          cd app
          CI=false npm run build

      - name: Deploy para a branch pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout --orphan pages
          git rm -rf .
          mv app/build/* .
          git add .
          git commit -m "Deploy automático para GitHub Pages"
          git push -f origin pages
